# Generated by Django 4.1.4 on 2022-12-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signed", models.BooleanField(default=False)),
            ],
            options={"verbose_name_plural": "Contract status",},
        ),
        migrations.AlterField(
            model_name="event",
            name="event_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_client",
                to="crm.contractstatus",
            ),
        ),
    ]
