# Generated by Django 4.1.4 on 2023-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_alter_event_attendees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_status",
            field=models.CharField(
                choices=[("In progress", "In Progress"), ("Ended", "Ended")],
                max_length=64,
                verbose_name="event_status",
            ),
        ),
    ]
