# Generated by Django 4.1.4 on 2023-03-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_alter_client_client_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
