# Generated by Django 4.1.4 on 2022-12-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("Manager", "Manager"),
                    ("Seller", "Seller"),
                    ("support", "Support"),
                ],
                max_length=64,
            ),
        ),
    ]
